# Generated by Django 5.0.7 on 2026-08-19 16:31

import apps.projects.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0002_story_is_official'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.projects.models.project_cover_upload_path)),
                ('project_type', models.CharField(choices=[('story', 'Story'), ('comic', 'Comic'), ('manga', 'Manga'), ('manhua', 'Manhua'), ('animation', 'Animation')], db_index=True, default='story', max_length=20)),
                ('art_style', models.CharField(choices=[('anime', 'Anime'), ('manga_bw', 'Manga (black & white / screentone)'), ('manhua', 'Manhua / Manhwa'), ('western_cartoon', 'Western cartoon'), ('semi_realistic', 'Semi-realistic'), ('custom', 'Custom')], db_index=True, default='anime', max_length=30)),
                ('art_style_description', models.TextField(blank=True, help_text='Free-text style description used when art_style is Custom.', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', max_length=15)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('story', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='stories.story')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='projects_owner_i_fc804a_idx'), models.Index(fields=['project_type', '-updated_at'], name='projects_project_93f2b7_idx')],
            },
        ),
    ]
