# Generated by Django 5.0.7 on 2026-08-17 12:47

import apps.chapters.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('chapter_number', models.PositiveIntegerField(db_index=True)),
                ('content', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated chapter summary', max_length=500)),
                ('ai_enhanced', models.BooleanField(default=False, help_text='Content enhanced by AI')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], db_index=True, default='draft', max_length=15)),
                ('is_premium', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('likes_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('comments_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='stories.story')),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['story', 'chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='AIImageGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(max_length=2000)),
                ('negative_prompt', models.TextField(blank=True, max_length=1000)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('provider', models.CharField(choices=[('dalle', 'DALL-E'), ('midjourney', 'Midjourney'), ('stable_diffusion', 'Stable Diffusion'), ('leonardo', 'Leonardo AI')], default='stable_diffusion', max_length=20)),
                ('width', models.PositiveIntegerField(default=1024)),
                ('height', models.PositiveIntegerField(default=1024)),
                ('steps', models.PositiveIntegerField(default=20)),
                ('guidance_scale', models.FloatField(default=7.5)),
                ('seed', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to=apps.chapters.models.chapter_image_upload_path)),
                ('error_message', models.TextField(blank=True)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='chapters.chapter')),
            ],
            options={
                'db_table': 'ai_image_generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.chapters.models.chapter_image_upload_path)),
                ('page_order', models.PositiveIntegerField(db_index=True)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('uploaded', 'User Uploaded'), ('ai_generated', 'AI Generated'), ('ai_enhanced', 'AI Enhanced')], default='uploaded', max_length=15)),
                ('ai_prompt', models.TextField(blank=True, max_length=1000)),
                ('ai_style', models.CharField(blank=True, max_length=50)),
                ('ai_provider', models.CharField(blank=True, max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_images', to='chapters.chapter')),
            ],
            options={
                'db_table': 'chapter_images',
                'ordering': ['chapter', 'page_order'],
            },
        ),
        migrations.CreateModel(
            name='ChapterLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_likes', to='chapters.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_chapters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chapter_likes',
            },
        ),
        migrations.CreateModel(
            name='ChapterView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('pages_viewed', models.PositiveIntegerField(default=1)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_views', to='chapters.chapter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chapter_views',
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('scroll_position', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('reading_time_minutes', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('bookmarked_position', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='chapters.chapter')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_progress',
            },
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['story', 'chapter_number'], name='chapters_story_i_03fd39_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['status', '-published_at'], name='chapters_status_2d903b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('story', 'chapter_number')},
        ),
        migrations.AddIndex(
            model_name='aiimagegeneration',
            index=models.Index(fields=['user', '-created_at'], name='ai_image_ge_user_id_1313bf_idx'),
        ),
        migrations.AddIndex(
            model_name='aiimagegeneration',
            index=models.Index(fields=['status', '-created_at'], name='ai_image_ge_status_7acc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterimage',
            index=models.Index(fields=['chapter', 'page_order'], name='chapter_ima_chapter_5b6eab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapterimage',
            unique_together={('chapter', 'page_order')},
        ),
        migrations.AddIndex(
            model_name='chapterlike',
            index=models.Index(fields=['user', '-created_at'], name='chapter_lik_user_id_4ee494_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapterlike',
            unique_together={('chapter', 'user')},
        ),
        migrations.AddIndex(
            model_name='chapterview',
            index=models.Index(fields=['chapter', '-viewed_at'], name='chapter_vie_chapter_888997_idx'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['user', '-last_read_at'], name='reading_pro_user_id_4bef0a_idx'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['story', '-last_read_at'], name='reading_pro_story_i_96068e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together={('user', 'story', 'chapter')},
        ),
    ]
