# Generated by Django 5.0.7 on 2026-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimagegeneration',
            name='image_type',
            field=models.CharField(choices=[('cover', 'Story Cover'), ('chapter', 'Chapter Illustration'), ('character', 'Character Art'), ('scene', 'Scene Art')], db_index=True, default='cover', max_length=20),
        ),
    ]
