# Generated by Django 5.0.7 on 2026-08-17 15:12

import apps.chapters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_aiimagegeneration_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimagegeneration',
            name='provider',
            field=models.CharField(choices=[('dalle', 'DALL-E'), ('midjourney', 'Midjourney'), ('stable_diffusion', 'Stable Diffusion'), ('leonardo', 'Leonardo AI'), ('stability', 'Stability AI (v2beta)'), ('local', 'Local placeholder (development)')], default='stable_diffusion', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiimagegeneration',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.chapters.models.ai_generation_result_path),
        ),
    ]
