# Generated by Django 5.0.7 on 2026-08-17 12:47

import apps.stories.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stories_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stories_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.stories.models.story_cover_upload_path)),
                ('ai_cover_prompt', models.TextField(blank=True, help_text='Prompt for AI cover generation', max_length=1000)),
                ('ai_cover_style', models.CharField(blank=True, help_text='AI art style (realistic, anime, comic, etc.)', max_length=50)),
                ('content_type', models.CharField(choices=[('novel', 'Novel'), ('short_story', 'Short Story'), ('web_novel', 'Web Novel'), ('comic', 'Comic'), ('manga', 'Manga'), ('manhua', 'Manhua')], db_index=True, max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ar', 'Arabic')], db_index=True, default='en', max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('hiatus', 'On Hiatus'), ('discontinued', 'Discontinued')], db_index=True, default='draft', max_length=15)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_premium', models.BooleanField(db_index=True, default=False)),
                ('ai_assistance_enabled', models.BooleanField(default=True, help_text='Allow AI to help with content generation')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chapters_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('likes_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('bookmarks_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('followers_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('comments_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('avg_reading_time', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_stories', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, related_name='stories', to='stories.genre')),
                ('tags', models.ManyToManyField(blank=True, related_name='stories', to='stories.tag')),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='stories.story')),
            ],
            options={
                'db_table': 'ai_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_usage_lo_user_id_3b96bc_idx'), models.Index(fields=['action', '-created_at'], name='ai_usage_lo_action_aa0975_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(max_length=2000)),
                ('negative_prompt', models.TextField(blank=True, max_length=1000)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('ai_provider', models.CharField(choices=[('dalle', 'DALL-E'), ('midjourney', 'Midjourney'), ('stable_diffusion', 'Stable Diffusion'), ('leonardo', 'Leonardo AI')], default='stable_diffusion', max_length=20)),
                ('image_type', models.CharField(choices=[('cover', 'Story Cover'), ('chapter', 'Chapter Illustration'), ('character', 'Character Art'), ('scene', 'Scene Art')], max_length=20)),
                ('image', models.ImageField(upload_to=apps.stories.models.ai_generated_image_path)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('seed', models.CharField(blank=True, max_length=50)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_images', to='stories.story')),
            ],
            options={
                'db_table': 'ai_generated_images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['story', '-created_at'], name='ai_generate_story_i_b764c2_idx'), models.Index(fields=['user', '-created_at'], name='ai_generate_user_id_e7593d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_bookmarks', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_bookmarks',
                'indexes': [models.Index(fields=['user', '-created_at'], name='story_bookm_user_id_363149_idx')],
                'unique_together': {('story', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_follows', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_follows',
                'indexes': [models.Index(fields=['user', '-created_at'], name='story_follo_user_id_fc2442_idx')],
                'unique_together': {('story', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_likes',
                'indexes': [models.Index(fields=['user', '-created_at'], name='story_likes_user_id_b38133_idx')],
                'unique_together': {('story', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to='stories.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story_views',
                'indexes': [models.Index(fields=['story', '-viewed_at'], name='story_views_story_i_ced952_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author', '-created_at'], name='stories_author__8b1995_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['content_type', '-published_at'], name='stories_content_c0b138_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status', '-views_count'], name='stories_status_a663ef_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-likes_count'], name='stories_likes_c_d8ee83_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-followers_count'], name='stories_followe_e4b58c_idx'),
        ),
    ]
