# Generated by Django 5.0.7 on 2026-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_official',
            field=models.BooleanField(db_index=True, default=False, help_text='Official Manji platform story (e.g. the MANJI welcome story).'),
        ),
    ]
