# Generated by Django 5.0.7 on 2026-08-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_backfill_projects_from_stories'),
        ('stories', '0002_story_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='projects.project'),
        ),
    ]
