# Generated by Django 5.0.7 on 2026-08-20 08:10

import apps.characters.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_backfill_projects_from_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(choices=[('protagonist', 'Protagonist'), ('antagonist', 'Antagonist'), ('supporting', 'Supporting'), ('mentor', 'Mentor'), ('villain', 'Villain'), ('minor', 'Minor'), ('other', 'Other')], default='supporting', max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('personality', models.TextField(blank=True)),
                ('backstory', models.TextField(blank=True)),
                ('appearance', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.characters.models.character_avatar_upload_path)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='projects.project')),
            ],
            options={
                'db_table': 'characters',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('enemy', 'Enemy'), ('love', 'Love interest'), ('rival', 'Rival'), ('ally', 'Ally'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('neutral', 'Neutral'), ('custom', 'Custom')], default='neutral', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='characters.character')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='characters.character')),
            ],
            options={
                'db_table': 'character_relationships',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='+', through='characters.CharacterRelationship', to='characters.character'),
        ),
        migrations.AddConstraint(
            model_name='characterrelationship',
            constraint=models.UniqueConstraint(fields=('from_character', 'to_character'), name='unique_character_relationship'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['project', 'order'], name='characters_project_fa3a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['project', 'role'], name='characters_project_9abe5c_idx'),
        ),
    ]
