# Generated by Django 5.0.7 on 2026-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate age of the character.', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, help_text='Free-form character notes kept out of the AI context prompt.'),
        ),
    ]
