# Generated by Django 5.0.7 on 2026-08-20 10:24

import apps.storyboard.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('scenes', '0002_scene_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryboardPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.storyboard.models.panel_image_upload_path)),
                ('shot', models.CharField(choices=[('establishing', 'Establishing'), ('wide', 'Wide'), ('medium', 'Medium'), ('close_up', 'Close-up'), ('extreme_close_up', 'Extreme close-up'), ('over_shoulder', 'Over-the-shoulder'), ('pov', 'POV'), ('two_shot', 'Two-shot')], default='medium', max_length=30)),
                ('camera_movement', models.CharField(choices=[('static', 'Static'), ('pan', 'Pan'), ('tilt', 'Tilt'), ('tracking', 'Tracking'), ('zoom', 'Zoom'), ('dolly', 'Dolly'), ('handheld', 'Handheld')], default='static', max_length=20)),
                ('aspect_ratio', models.CharField(choices=[('1:1', 'Square (1:1)'), ('16:9', 'Standard (16:9)'), ('9:16', 'Tall (9:16)'), ('portrait', 'Manga page (portrait)'), ('21:9', 'Ultrawide (21:9)')], default='16:9', max_length=10)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Approximate shot length in seconds.', null=True)),
                ('dialogue', models.TextField(blank=True)),
                ('narration', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Optional library asset to use as the plate/background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storyboard_panels', to='assets.asset')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='scenes.scene')),
            ],
            options={
                'db_table': 'storyboard_panels',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['scene', 'order'], name='storyboard__scene_i_49f683_idx')],
            },
        ),
    ]
