# Generated by Django 5.0.7 on 2026-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyboardpanel',
            name='shot',
            field=models.CharField(choices=[('wide', 'Wide Shot'), ('medium', 'Medium Shot'), ('close_up', 'Close-Up'), ('extreme_close_up', 'Extreme Close-Up'), ('over_shoulder', 'Over-the-Shoulder'), ('pov', 'POV'), ('establishing', 'Establishing Shot'), ('tracking', 'Tracking Shot'), ('aerial', 'Aerial'), ('two_shot', 'Two-shot')], default='medium', max_length=30),
        ),
    ]
