# Generated by Django 5.0.7 on 2026-09-01 10:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenes', '0002_scene_cast'),
        ('characters', '0002_character_age_character_notes'),
        ('users', '0002_user_is_official'),
        ('projects', '0002_backfill_projects_from_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('kind', models.CharField(choices=[('dialogue', 'Dialogue'), ('voice_over', 'Voice-over'), ('music', 'Music'), ('sfx', 'Sound effect')], default='dialogue', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='audio/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.BigIntegerField(default=0)),
                ('duration', models.FloatField(default=0, help_text='Duration in seconds.')),
                ('dialogue_line', models.CharField(blank=True, default='', help_text='The spoken line / dialogue text this clip reads.', max_length=500)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Timeline placement order within a scene.')),
                ('start_seconds', models.FloatField(default=0, help_text='Timeline start offset in seconds.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, help_text='Character whose voice this clip represents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_recordings', to='characters.character')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='users.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='projects.project')),
                ('scene', models.ForeignKey(blank=True, help_text='Scene this clip is placed in (timeline attachment).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_recordings', to='scenes.scene')),
            ],
            options={
                'db_table': 'voice_recordings',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voicerecording',
            index=models.Index(fields=['project', 'scene', 'order'], name='voice_proj_scene_idx'),
        ),
        migrations.AddIndex(
            model_name='voicerecording',
            index=models.Index(fields=['project', 'character'], name='voice_proj_char_idx'),
        ),
        migrations.AddConstraint(
            model_name='voicerecording',
            constraint=models.UniqueConstraint(condition=models.Q(('scene__isnull', False)), fields=('scene', 'order'), name='uniq_voice_scene_order'),
        ),
    ]