# Generated by Django 5.0.7 on 2026-09-18 09:49

import apps.official.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0003_alter_aiimagegeneration_provider_and_more'),
        ('scenes', '0003_scene_camera_type'),
        ('stories', '0003_aiusagelog_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialArc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.official.models.official_cover_upload_path)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'official_arcs',
                'ordering': ['season', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OfficialSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_number', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.official.models.official_cover_upload_path)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'official_seasons',
                'ordering': ['series', 'season_number'],
            },
        ),
        migrations.CreateModel(
            name='OfficialAnimation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.official.models.official_cover_upload_path)),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animations', to='official.officialarc')),
            ],
            options={
                'db_table': 'official_animations',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OfficialEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.official.models.official_thumbnail_upload_path)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=apps.official.models.official_video_upload_path)),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, CDN, etc.)', max_length=500)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='official.officialanimation')),
            ],
            options={
                'db_table': 'official_episodes',
                'ordering': ['animation', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='OfficialChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_chapter_meta', to='chapters.chapter')),
                ('animation_episode', models.ForeignKey(blank=True, help_text='Corresponding animation episode, if adapted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_official_chapters', to='official.officialepisode')),
            ],
            options={
                'db_table': 'official_chapters',
                'ordering': ['official_story', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OfficialAnimationScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('start_time', models.PositiveIntegerField(help_text='Start time in seconds from episode start')),
                ('end_time', models.PositiveIntegerField(blank=True, help_text='End time in seconds', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.official.models.official_thumbnail_upload_path)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animation_scenes', to='official.officialepisode')),
            ],
            options={
                'db_table': 'official_animation_scenes',
                'ordering': ['episode', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OfficialScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation_scene', models.ForeignKey(blank=True, help_text='Corresponding animation scene, if adapted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_official_scenes', to='official.officialanimationscene')),
                ('official_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_scenes', to='official.officialchapter')),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_scene_meta', to='scenes.scene')),
            ],
            options={
                'db_table': 'official_scenes',
                'ordering': ['official_chapter', 'order'],
            },
        ),
        migrations.AddField(
            model_name='officialarc',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='official.officialseason'),
        ),
        migrations.CreateModel(
            name='OfficialSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.official.models.official_cover_upload_path)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'official_series',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='official_se_is_acti_980d83_idx')],
            },
        ),
        migrations.AddField(
            model_name='officialseason',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='official.officialseries'),
        ),
        migrations.AddField(
            model_name='officialanimation',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='official.officialseries'),
        ),
        migrations.CreateModel(
            name='OfficialStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_canon', models.BooleanField(default=True, help_text='Part of main continuity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_stories', to='official.officialarc')),
                ('story', models.OneToOneField(help_text='The underlying Story record (read-only for normal users).', on_delete=django.db.models.deletion.CASCADE, related_name='official_story_meta', to='stories.story')),
            ],
            options={
                'db_table': 'official_stories',
                'ordering': ['arc', 'order'],
            },
        ),
        migrations.AddField(
            model_name='officialchapter',
            name='official_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_chapters', to='official.officialstory'),
        ),
        migrations.CreateModel(
            name='OfficialBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('chapter', 'Official Chapter'), ('episode', 'Official Episode'), ('arc', 'Official Arc'), ('story', 'Official Story')], db_index=True, max_length=10)),
                ('content_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'official_bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'content_type'], name='official_bo_user_id_722abf_idx')],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='OfficialContentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('chapter', 'Official Chapter'), ('episode', 'Official Episode')], db_index=True, max_length=10)),
                ('content_id', models.UUIDField(db_index=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('current_position', models.PositiveIntegerField(default=0, help_text='Seconds for video, scroll for text')),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'official_content_progress',
                'indexes': [models.Index(fields=['user', 'content_type', 'completed'], name='official_co_user_id_76f443_idx')],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='OfficialContentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('series', 'Official Series'), ('season', 'Official Season'), ('arc', 'Official Arc'), ('story', 'Official Story'), ('chapter', 'Official Chapter'), ('animation', 'Official Animation'), ('episode', 'Official Episode')], db_index=True, max_length=15)),
                ('content_id', models.UUIDField(db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Seconds spent viewing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'official_content_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id', '-viewed_at'], name='official_co_content_5a9609_idx'), models.Index(fields=['user', '-viewed_at'], name='official_co_user_id_ee4ac8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='officialepisode',
            index=models.Index(fields=['animation', 'is_published', 'episode_number'], name='official_ep_animati_2b7972_idx'),
        ),
        migrations.AddConstraint(
            model_name='officialepisode',
            constraint=models.UniqueConstraint(fields=('animation', 'episode_number'), name='unique_episode_per_animation'),
        ),
        migrations.AddIndex(
            model_name='officialanimationscene',
            index=models.Index(fields=['episode', 'order'], name='official_an_episode_1c7978_idx'),
        ),
        migrations.AddIndex(
            model_name='officialscene',
            index=models.Index(fields=['official_chapter', 'order'], name='official_sc_officia_76b8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='officialarc',
            index=models.Index(fields=['season', 'is_published', 'order'], name='official_ar_season__d04448_idx'),
        ),
        migrations.AddIndex(
            model_name='officialseason',
            index=models.Index(fields=['series', 'is_published', 'season_number'], name='official_se_series__ef826a_idx'),
        ),
        migrations.AddConstraint(
            model_name='officialseason',
            constraint=models.UniqueConstraint(fields=('series', 'season_number'), name='unique_season_per_series'),
        ),
        migrations.AddIndex(
            model_name='officialanimation',
            index=models.Index(fields=['is_published', 'order'], name='official_an_is_publ_c19ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='officialstory',
            index=models.Index(fields=['arc', 'order'], name='official_st_arc_id_26c192_idx'),
        ),
        migrations.AddIndex(
            model_name='officialchapter',
            index=models.Index(fields=['official_story', 'is_published', 'order'], name='official_ch_officia_1d0366_idx'),
        ),
    ]
