# Generated by Django 5.0.7 on 2026-08-20 19:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_backfill_projects_from_stories'),
        ('scenes', '0002_scene_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('fps', models.PositiveSmallIntegerField(default=12, help_text='Playback frame rate (frames per second).')),
                ('width', models.PositiveIntegerField(default=960)),
                ('height', models.PositiveIntegerField(default=540)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='projects.project')),
                ('scene', models.ForeignKey(blank=True, help_text='The source scene this animation is built from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animations', to='scenes.scene')),
            ],
            options={
                'db_table': 'animation_projects',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimationLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('background', 'Background'), ('character', 'Character'), ('effects', 'Effects'), ('scene', 'Scene'), ('camera', 'Camera')], default='character', max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='animation.animationproject')),
            ],
            options={
                'db_table': 'animation_layers',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimationFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(db_index=True)),
                ('layers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='animation.animationproject')),
            ],
            options={
                'db_table': 'animation_frames',
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='animationproject',
            index=models.Index(fields=['project', 'order'], name='animation_p_project_59cfae_idx'),
        ),
        migrations.AddIndex(
            model_name='animationlayer',
            index=models.Index(fields=['animation', 'order'], name='animation_l_animati_797045_idx'),
        ),
        migrations.AddConstraint(
            model_name='animationframe',
            constraint=models.UniqueConstraint(fields=('animation', 'index'), name='uniq_animation_frame_index'),
        ),
    ]
