# Generated by Django 5.0.7 on 2026-09-09 11:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episodes/')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Approximate duration in seconds.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=15)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='animation.animationproject')),
            ],
            options={
                'db_table': 'animation_episodes',
                'ordering': ['episode_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('animation', 'episode_number'), name='uniq_episode_animation_number'),
        ),
    ]
