# Generated by Django 5.0.7 on 2026-08-20 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('projects', '0002_backfill_projects_from_stories'),
        ('stories', '0002_story_is_official'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='stories.story'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'project', '-updated_at'], name='ai_aiconver_user_id_d37bab_idx'),
        ),
    ]
