# Generated by Django 5.0.7 on 2026-08-20 07:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0003_alter_aiimagegeneration_provider_and_more'),
        ('projects', '0002_backfill_projects_from_stories'),
        ('stories', '0002_story_is_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('characters', models.JSONField(blank=True, default=list)),
                ('dialogue', models.TextField(blank=True)),
                ('narration', models.TextField(blank=True)),
                ('camera_notes', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Approximate duration in seconds.', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='chapters.chapter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='projects.project')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='stories.story')),
            ],
            options={
                'db_table': 'scenes',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['project', 'order'], name='scenes_project_bf391d_idx'), models.Index(fields=['chapter', 'order'], name='scenes_chapter_cf6914_idx')],
            },
        ),
    ]
