# Generated by Django 5.0.7 on 2026-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='characters.character'),
        ),
    ]
