# Generated by Django 5.0.7 on 2026-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_scene_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='camera_type',
            field=models.CharField(blank=True, choices=[('wide_shot', 'Wide Shot'), ('medium_shot', 'Medium Shot'), ('close_up', 'Close-Up'), ('extreme_close_up', 'Extreme Close-Up'), ('over_the_shoulder', 'Over-the-Shoulder'), ('pov', 'POV'), ('establishing_shot', 'Establishing Shot'), ('tracking_shot', 'Tracking Shot'), ('aerial', 'Aerial')], db_index=True, max_length=30),
        ),
    ]
