# Generated by Django 5.0.7 on 2026-08-19 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_is_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tour_state', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post_registration', models.CharField(choices=[('none', 'Not prompted'), ('prompted', 'Prompted'), ('skipped', 'Skipped'), ('completed', 'Completed')], db_index=True, default='none', max_length=15)),
                ('post_registration_prompted_at', models.DateTimeField(blank=True, null=True)),
                ('post_registration_answered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_tours', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tour_state',
            },
        ),
    ]
